### PR TITLE
chore: bump @polkadot

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Fix
- [ ] Feature
- [ ] Refactoring
- [x] Chore

### What's new?

- [x] bump `@polkadot` packages. related to https://github.com/kodadot/nft-gallery/issues/3966

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR
- [ ] I've written some unit tests 🧪

### Optional

- [ ] I found edge cases

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### CODE REVIEW

**Review by roiLeo — APPROVED** [review]
yolo

**Comment by roiLeo** [comment]
ping @vikiival

**Comment by vikiival** [comment]
Thanks I will update sub-api!

**Comment by vikiival** [comment]
Thanks for the ping @roiLeo 🤗

released

> 📦  @kodadot1/sub-api@0.1.1-alpha.4

please bump all @polkadot-js related packages to latest in the nft-gallery

**Comment by roiLeo** [comment]
Hey @vikiival! did you publish it?

**Comment by vikiival** [comment]
> Published 5 minutes ago

https://www.npmjs.com/package/@kodadot1/sub-api

yup

**Comment by roiLeo** [comment]
lol I'm stuck in a cached version
Screenshot 2022-12-14 at 15-15-47 @kodadot1_sub-api

**Comment by vikiival** [comment]
Screenshot 2022-12-14 at 15 21 45

**Pull request merged**
