### PR TITLE
chore: put polkadot packages to peer

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot NFT gallery](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Fix
- [ ] Feature
- [ ] Refactoring
- [x] Chore

### What's new?

- [x] related https://github.com/kodadot/nft-gallery/issues/4585

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR
- [ ] I've written some unit tests 🧪

### Optional

- [ ] I found edge cases

### Had issue bounty label?

- [ ] Fill up your KSM address: [Payout](https://beta.kodadot.xyz/transfer/?target=<My_Kusama_Address_check_https://github.com/kodadot/nft-gallery/blob/main/CONTRIBUTING.md#creating-your-ksm-address>)

### Community participation

- [x] [Are you at KodaDot Discord?](https://discord.gg/35hzy2dXXh)

### CODE REVIEW

**Comment by vikiival** [comment]
> the version will depend on the consumer side?

So if someone would like to use `sub-api` they would need to install additional package?

**Comment by preschian** [comment]
> > the version will depend on the consumer side?
> 
> So if someone would like to use `sub-api` they would need to install additional package?

yes, just following what paraspell did. wdyt?

- https://github.com/paraspell/xcm-sdk/blob/main/package.json#L38-L43
- https://github.com/paraspell/xcm-sdk#install-deps-via-npmyarnpnpm

**Comment by vikiival** [comment]
So lets do a compromise 

@preschian please do an update of package and lets move deps in separated PR

**Comment by vikiival** [comment]
cc @preschian ?

**Comment by preschian** [comment]
> So lets do a compromise
> 
> @preschian please do an update of package and lets move deps in separated PR

sure, updated in this PR https://github.com/kodadot/packages/pull/140

**Comment by vikiival** [comment]
Let's resolve conflicts?

Screenshot 2023-05-14 at 16 15 20

**Comment by roiLeo** [comment]
is it still relevant?

**Comment by preschian** [comment]
> is it still relevant?

oh, kinda missed this one. yes, wdyt?
in case we face this error again https://github.com/kodadot/nft-gallery/issues/4585

**Comment by vikiival** [comment]
Yup just bump versions and we can merge

**Pull request closed without merging**
