### PR TITLE
add turborepo

### LINKED ISSUE #20: Can we have Turborepo at home?
https://turborepo.org

### PR DESCRIPTION
**Pull request by preschian**
- setup pnpm workspace - https://pnpm.io/workspaces
- add turborepo - https://turborepo.org/docs/getting-started/existing-monorepo
- fixes #20 
- add tuborepo (build|test|lint) into github actions

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
Hey please do a lint in the sepatated PR, this is too big for one PR

**Comment by preschian** [comment]
> Hey please do a lint in the sepatated PR, this is too big for one PR

oops, good idea. I put them in separate PR https://github.com/kodadot/packages/pull/66

**Review by vikiival — APPROVED** [review]

**Comment by vikiival** [comment]
Is something that I need to setup to make it work?

**Comment by preschian** [comment]
> Is something that I need to setup to make it work?

added some readme, hope that helps. let me know if you face some error

and, I keep the current folder structure. I think the current folder structure is already good and it minimizes the changes. instead of previous changes, I moved all folders under `libs/`

**Pull request closed without merging**
