### PR TITLE
🔧 destroy collection rmrk2

### LINKED ISSUE #179: DESTROY interaction rmrk2
- Inside https://github.com/kodadot/packages/blob/dc3a21d0f16ad8bdcf398afbcf8526a5f7763787/minimark/src/rmrk/v2/helper.ts#L12

### PR DESCRIPTION
**Pull request by roiLeo**
## PR Type

- [x] Bugfix

## Context

- [x] Closes #179 
- [x] Requires for kodadot/nft-gallery#7960

### CODE REVIEW

**Comment by vikiival** [comment]
Please ping me next time

**Comment by vikiival** [comment]
Sadly there is not such thing as Destroy in the RMRK 1 /2 spec

Screenshot 2023-11-17 at 14 23 04


The only possible implementation is to change issuer to the address 
I created address

`DbinrqVnBgjspg7sWtUZkAnA1agsmjcfq5NmSuknmWTKvVX` (the bin ;D)

**Comment by vikiival** [comment]
But we can do the destory interaction as it is deprecated by RMRK team

**Comment by roiLeo** [comment]
> Please ping me next time

yessir 👍 

> Sadly there is not such thing as Destroy in the RMRK 1 /2 spec

rmrk2?: 
- https://github.com/rmrk-team/rmrk-spec/blob/master/standards/rmrk2.0.0/interactions/destroy.md
- https://github.com/rmrk-team/rmrk-substrate/blob/8c74166627c496435e2dff5dbea03a55d8fec764/docs/pallets/rmrk-core-calls.md#destroy_collection

> The only possible implementation is to change issuer to the address I created address
> 
> `DbinrqVnBgjspg7sWtUZkAnA1agsmjcfq5NmSuknmWTKvVX` (the bin ;D)

Transfer collection to address? Is it even possible?

**Comment by vikiival** [comment]
> rmrk2?:

I apologize,this must have slipped  through in front of my eyes

**Comment by roiLeo** [comment]
@vikiival do you mind publishing new minimark version?

**Comment by vikiival** [comment]
```
@kodadot1/minimark@0.1.11
```

**Pull request merged**
